version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  sqlserver:
    image: ball/database:1.0
    container_name: sqlserver
    build: Database
    volumes:
      - sqlserverdata:/var/opt/mssql
    ports:
      - "1434:1433"

  inventoryqueries:
    image: ball/inventoryqueries:1.0
    build: InventoryQueries
    container_name: inventoryqueries
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - DOTNET_ENVIRONMENT=Production
    ports:
      - "8086:80"
  
  inventorycommands:
    image: ball/inventorycommands:1.0
    build: InventoryCommands
    container_name: inventorycommands
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - DOTNET_ENVIRONMENT=Production
    ports:
      - "8087:80"
      
  ballorder:
    image: ball/ballorder:1.0
    build: Order/BallOrder
    container_name: ballorder
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - DOTNET_ENVIRONMENT=Production
    ports:
      - "8084:80"
    
  paymentAPI:
    image: ball/paymentsapi:1.0
    build: Payment
    container_name: paymentAPI
    depends_on:
       - rabbitmq
       - sqlserver
    environment:
       - DOTNET_ENVIRONMENT=Production
    ports:
       - "8085:80"

  authentication:
    image: ball/authentication:1.0
    build: Authentication
    container_name: authentication
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "8081:80"

  gateway:
    image: ball/gateway:1.0
    build: Gateway
    container_name: gateway
    ports:
      - "80:80"

  names:
    image: ball/names:1.0
    build: NameService
    container_name: names
    ports:
      - "8088:80"

  shipping:
    image: ball/shipping:1.0
    build: Shipping
    container_name: shipping
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "8082:80"

  support:
    image: ball/support:1.0
    build: Support
    container_name: support
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "8089:80"

  shoppingqueries:
    image: ball/shoppingyqueries:1.0
    build: Shopping/ShoppingQuery
    container_name: shoppingqueries
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - DOTNET_ENVIRONMENT=Production
    ports:
      - "8090:80"
  
  shoppingcommands:
    image: ball/shoppingcommands:1.0
    build: Shopping/ShoppingCommand
    container_name: shoppingcommands
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - DOTNET_ENVIRONMENT=Production
    ports:
      - "8083:80"

volumes:
  sqlserverdata:
  rabbitmqdata:
