zuul:
  routes:
    auth:
      path: /auth/**
      url: http://authentication:80/api/auth
    shipment:
      path: /shipments/**
      url: http://shipping:80/api/shipments
    shop:
      path: /shop/**
      url: http://localhost:8083/api/shop
    order:
      path: /order/**
      url: http://ballorder:80/api/order
    payment:
      path: /payment/**
      url: http://paymentAPI:80/api/payment
    inventory:
      path: /product/**
      url: http://localhost:8086/api/product
    support:
      path: /support/**
      url: http://support:80
gateway:
  header:
    token: X-Token
    payload: X-Token-Payload
  target:
    path: permit
    query: target
  ws:
    handlers:
      -
        prefix: support-**
        url: http://support:80/chat
  filters:
    # AUTHENTICATION Service
    -
      path: /auth/**
      roles:
        - EMPLOYEE
        - CUSTOMER
        - SUPPLIER
    # SHIPMENT Service
    -
      path: /shipments/**
      roles:
        - EMPLOYEE
    # ORDER Service
    -
      path: /order/**
      method: POST
      roles:
        - EMPLOYEE
    -
      path: /order/**
      roles:
        - EMPLOYEE
        - CUSTOMER
    -
      path: /order/**
      method: UPDATE
      roles:
        - EMPLOYEE
    # INVENTORY Service
    -
      path: /product/internal
      method: POST
      roles:
        - EMPLOYEE
    -
      path: /product/supplier
      method: POST
      roles:
        - SUPPLIER
    -
      path: /product/internal/stock/**
      method: PUT
      roles:
        - EMPLOYEE
    -
      path: /product/supplier/stock/**
      method: PUT
      roles:
        - SUPPLIER
    # PAYMENT Service
    -
      path: /api/payment/**
      roles:
        - EMPLOYEE
server:
  port: 80
